# Apache Configuration
---
- name: Install Apache2
  apt:
    pkg: ['apache2', 'libapache2-mod-php']
    update_cache: yes
    cache_valid_time: 86400
    state: present

- name: Install MySQL-Client
  apt:
    pkg: 'mysql-client'
    update_cache: yes
    cache_valid_time: 86400
    state: present

- name: Add listening port for Apache virtualhost
  template:
    src: "files/ports.conf.j2"
    dest: "/etc/apache2/ports.conf"  

- name: Set up Apache virtualhost
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/apache2/sites-available/wordpress.conf"

- name: Enable new site
  shell: /usr/sbin/a2ensite wordpress.conf

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: restart apache2
...