---
- name: DB server
  hosts: db
  roles:
    - php
    - firewall
    - mysql
  vars:
    ufw_proto: tcp
    ufw_port: 80

- name: WEB server
  hosts: web
  roles:
    - php
    - firewall
    - apache
    - wordpress
  vars:
    ufw_proto: tcp
    ufw_port: 80
...
