---
- name: DB server
  hosts: db
  roles:
    - { role: php,  tags: php_db }
    - { role: firewall,  tags: firewall_db }
    - { role: mysql,  tags: mysql_db }
  vars:
    ufw_proto: tcp
    ufw_port: 3306

- name: WEB server
  hosts: web
  roles:
    - { role: php,  tags: php_web }
    - { role: firewall,  tags: firewall_web }
    - { role: apache,  tags: apache_web }
    - { role: wordpress,  tags: wordpress_web }
  vars:
    ufw_proto: tcp
    ufw_port: 8000
...
