# WordPress Configuration
---
- name: Download and unpack latest WordPress
  unarchive:
    src: "https://wordpress.org/latest.tar.gz"
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"

- name: Set up wp-config
  template:
    src: "../files/wp-config.php.j2"
    dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"

- name: Update WordPress config file
  lineinfile:
    path: "/var/www/{{ http_host }}/wordpress/wp-config.php"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{mysql_db}}' );"}
    - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{mysql_user}}' );"}
    - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{mysql_password}}' );"}
    - {'regexp': "define\\( 'DB_HOST', '(.)+' \\);", 'line': "define( 'DB_HOST', '{{mysql_host}}' );"}

- name: Restart Apache2
  service:
    name: apache2
    state: restarted
... 


