# - name: Wordpress | Install php
#   apt:
#     pkg: ['php-pear', 'php-fpm', 'php-dev', 'php-zip', 'php-curl',
#           'php-xmlrpc', 'php-gd', 'php-mysql', 'php-mbstring', 'php-xml']
#     update_cache: yes
#     cache_valid_time: 86400
#     state: present

---
- name: Install prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

- name: install PHP for MySQL
  apt: name={{item}} state=present
  with_items:
    - php
    - php-curl
    - php-mbstring
    - php-xml
    - php-soap
    - php-intl
    - php-zip
    - php-mysql
    - php-gd
    - python3-pymysql
    - libapache2-mod-php
